version: "3"
services:
  logseq:
    build:
      context: logseq
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - journal:/var/logseq
    cap_add:
      - SYS_ADMIN

volumes:
  logseq:
